name: CD

on:
  workflow_run:
    workflows: ["DevSecOps"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t kayok/helloworld:latest .
          docker push kayok/helloworld:latest

      # ถ้าเป็น deploy server (SSH) ให้เพิ่มตัวอย่างดังนี้
      # - name: Deploy to server
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       docker pull kayok/helloworld:latest
      #       docker stop helloworld || true
      #       docker rm helloworld || true
      #       docker run -d --name helloworld -p 8080:8080 kayok/helloworld:latest
